implement new sample filename scheme in dae/. daemon/ updated too but not tested (compile fine). Update opcontrol but still use the old  --ctr syntax to specify events. 2.4 daemon seems to run fine but not already stressed.
I updated TODO by mentionning all broken things but
surely not exhaustive.

regards,
Phil

diff --git a/utils/opcontrol b/utils/opcontrol
--- a/utils/opcontrol
+++ b/utils/opcontrol
@@ -196,13 +196,13 @@ do_init() {
 	DIR="/var/lib/oprofile"
 	LOCK_FILE="/var/lib/oprofile/lock"
 	LOG_FILE="$DIR/oprofiled.log"
-	SAMPLES_DIR="$DIR/samples/"
+	SAMPLES_DIR="$DIR/samples"
+	CURRENT_SAMPLES_DIR=${SAMPLES_DIR}/current
 	if test "$KERNEL_SUPPORT" = "yes"; then
 		MOUNT="/dev/oprofile"
 		DEVICE_FILE="$MOUNT/buffer"
 	else
 		MOUNT="/proc/sys/dev/oprofile"
-		SAMPLES_DIR="$DIR/samples/"
 		DEVICE_FILE="$DIR/opdev"
 		NOTE_DEVICE_FILE="$DIR/opnotedev"
 		HASH_MAP_DEVICE_FILE="$DIR/ophashmapdev"
@@ -878,7 +878,7 @@ do_setup() {
 		create_devices_24
 	fi
 
-	create_dir "$SAMPLES_DIR"
+	create_dir "$CURRENT_SAMPLES_DIR"
 }
 
 
@@ -1065,40 +1065,26 @@ hup_daemon() {
 
 #move all the sample files to a sample directory
 do_save_session () {
-	SAVE_DIR="${SAMPLES_DIR}${SAVE_NAME}"
+	SAVE_DIR="${SAMPLES_DIR}/${SAVE_NAME}"
 
 	if test -e "$SAVE_DIR"; then
 		echo "session $SAVE_DIR already exists" >&2
 		exit 1
 	fi
 		
-	#create directory
-	mkdir -p "$SAVE_DIR"
+	mv $CURRENT_SAMPLES_DIR $SAVE_DIR
 	if [ "$?" != "0" ]; then
-		echo "Couldn't mkdir -p $SAVE_DIR" >&2
+		echo "Couldn't move $CURRENT_SAMPLES_DIR to $SAVE_DIR" >&2
 		exit 1
 	fi
-
-	#move all the sample files to the directory
-	SAMPLE_FILES=`ls $SAMPLES_DIR`
-	for f in $SAMPLE_FILES; do
-		if test -f "${SAMPLES_DIR}${f}"; then
-			mv ${SAMPLES_DIR}${f} $SAVE_DIR
-		fi
-	done
 
 	hup_daemon
 }
 
 
-#remove all the sample files, but leave the session directories alone
+#remove all the sample files
 do_reset() {
-	SAMPLE_FILES=`ls $SAMPLES_DIR`
-	for f in $SAMPLE_FILES; do
-		if test -f "${SAMPLES_DIR}${f}"; then
-			rm ${SAMPLES_DIR}${f}
-		fi
-	done
+	rm -rf $CURRENT_SAMPLES_DIR
 
 	hup_daemon
 }
